apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.operator_namespace }} 
  annotations:
    argocd.argoproj.io/sync-wave: "-6"     
spec:
  {{- toYaml .Values.spec | nindent 2 }}