apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: common-service-edb
  namespace: {{ .Values.common_services_namespace }} 
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-10" | quote }}  
spec:
  requests:
    - operands:
        - name: cloud-native-postgresql
        - name: ibm-licensing-operator
          bindings:
            public-api-upload:
              secret: ibm-licensing-upload-token
              configmap: ibm-licensing-upload-config
      registry: common-service